version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

formatters:
  enable:
    - gofmt
    - gci
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule

issues:
  exclude-use-default: false
